### PR TITLE
Allow for null baseline_sha

### PR DESCRIPTION
**Pull request by dberenbaum**
Needed for https://github.com/iterative/dvclive/pull/646 to work without a baseline revision (since this would be a pain to provide in a no-git scenario).

@daavoo I will likely need your help to make similar changes on the Studio side to accept requests with missing `baseline_sha`.

### CODE REVIEW

**Review by daavoo — COMMENTED** [review]
Can we use just a 40-character placeholder string like `"z" * 40`?

**Comment by dberenbaum** [comment]
> Can we use just a 40-character placeholder string like `"z" * 40`?

The schema checks for a valid sha here:

https://github.com/iterative/dvc-studio-client/blob/535c3aa5ec1742f693466089418b656b4601d1f1/src/dvc_studio_client/schema.py#L9

**Comment by shcheklein** [comment]
@dberenbaum is it still relevant?

**Comment by dberenbaum** [comment]
It depends on how we decide to go with issues like https://github.com/iterative/dvclive/issues/638 and https://github.com/iterative/dvclive/issues/237. If we decide to clone the repo on every node where dvclive runs, then this won't be needed, but if we decided to allow for some "no-git" scenarios, I think it might be needed. I can convert to draft until we decide.

**Pull request closed without merging**
