### PR TITLE
add support for DVC_STUDIO_TOKEN and DVC_STUDIO_URL envvar

### LINKED ISSUE #23: STUDIO_ENDPOINT should be a base_url now
Since we have multiple APIs now, STUDIO_ENDPOINT should be a base url instead of an API endpoint for live metrics.

https://github.com/iterative/dvc-studio-client/blob/485b2d8baf056882f6c7cb59438208390a045998/src/dvc_studio_client/post_live_metrics.py#L180

### PR DESCRIPTION
**Pull request by skshetry**
- Adds support for `DVC_STUDIO_TOKEN` envvar and is given higher priority than `STUDIO_TOKEN`
- Adds support for `DVC_STUDIO_URL` base url for providing alternative url to the Studio instance.
- Keeps backward compatibility with `STUDIO_ENDPOINT` envvar. The side effect of this change is that `STUDIO_ENDPOINT` can be either relative or absolute. If the path is absolute, it will get higher precedence and that url will be used. If the path is relative, it will be joined with the studio url, either from the default or one specified through envvar.
- Replaces `STUDIO_TOKEN` from tests with `DVC_STUDIO_TOKEN`.
- Adds a test that `STUDIO_TOKEN` still works.
- Removes usages of `STUDIO_ENDPOINT` from the tests, and replaced with `DVC_STUDIO_URL`.

Closes #23.

### CODE REVIEW

**Review by daavoo — APPROVED** [review]

**Comment by skshetry** [comment]
You can still use STUDIO_ENDPOINT, nothing has changed. But you should prefer `DVC_STUDIO_URL` to API_URL now.

**Comment by dberenbaum** [comment]
When would you choose one over the other? If @dacbd is asking about best practices, wouldn't `DVC_STUDIO_URL` be better than `STUDIO_ENDPOINT` for a custom deployment since it's not specific to an endpoint?

**Comment by skshetry** [comment]
After this PR, we should consider `STUDIO_ENDPOINT` as deprecated and to be removed in the future.

**Comment by skshetry** [comment]
It was never documented.

**Comment by dacbd** [comment]
I should clarify, with `DVC_STUDIO_URL` an expected value can be: `https://studio.iterative.ai/api/live` like it was with `STUDIO_ENDPOINT` as opposed to something like `https://studio.iterative.ai/`

**Comment by skshetry** [comment]
With base url, it is not limited to just the hostname/netloc though. If the server is running at the base url: `https://shared.server.com/backend/`, that would work too. It probably does not matter to us, but wanted to clarify that it is really a base url, not just the netloc.

**Pull request merged**
